### ISSUE TITLE
android 11 反射不了这个方法了： setHiddenApiExemptions

### ISSUE THREAD

**Issue by jiangchaochao** [arpsyalin/practice#1]
android 11 反射不了这个方法了： setHiddenApiExemptions

java.lang.reflect.InvocationTargetException

**Comment by TheMelody** [comment]
> android 11 反射不了这个方法了： setHiddenApiExemptions
> 
> java.lang.reflect.InvocationTargetException

好像android11改了什么东西，setHiddenApiExemptions无法执行通过

**Comment by jiangchaochao** [comment]
可以的，后面再看吧
